#+TITLE: vagrant-vocab-conversion

* Introduction

The development environment for the vocab conversion
script. Assumption is that a Ubuntu/Debian compactible system is
available (use vagrant if on windows). Otherwise the bootstrap.sh
script will indicate what is needed for the most part.

Outside of the vagrant environment, configure will check what is
installed, etc. and fill in the appropriate values in the various .in
files (or flag an error if something is missing).

* Script

Uses:
- Python 3
- [[http://rdflib.readthedocs.org/en/stable/index.html][Rdflib]] for RDF operations
- [[https://secure.simplistix.co.uk/svn/xlrd/trunk/xlrd/doc/xlrd.html?p=4966][xlrd]] for parsing the excel input files.

* Usage

The first time it will be necessary to pregenerate some files using
the following commands.

#+BEGIN_SRC bash
autoconf
./configure
#+END_SRC

There after all that should be required is to use "make" in the same
directory (in the vagrant environment this is the /vagrant directory).
Any updates the .in script and configure.ac files will be picked up.

* Adding new scripts

It should be possible to extend the Makefile.in with new targets for
the build.

* End result

Can be found in the 'data.ttl' file.

* TODOs

Include build option for:

https://pythonhosted.org/django-jython/war-deployment.html


